sonar.projectKey=anzencore
sonar.organization=gianfrancoarocutipa
sonar.projectName=AnzenCore
sonar.sources=src, agent, mobile, app
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**, **/.venv/**, **/assets/**, tests/**