sonar.projectKey=anzencore
sonar.projectName=AnzenCore
sonar.sources=app,src
sonar.tests=tests
sonar.language=py
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**, **/.venv/**, **/assets/**, mobile/**
sonar.test.inclusions=tests/**/*.py
sonar.qualitygate.wait=true